# Generated by Django 2.2 on 2019-11-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191123_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='start',
            field=models.DateTimeField(null=True),
        ),
    ]
